# generated by fastapi-codegen:
#   filename:  api.yaml
#   timestamp: 2024-01-06T11:35:49+00:00

from __future__ import annotations

from datetime import datetime
from typing import Optional, Union

from fastapi import FastAPI

from models import SearchGetResponse, SearchGetResponse1, SearchGetResponse2


app = FastAPI(
    title='Fever Providers API',
    version='1.0.0',
    servers=[
        {
            'description': 'SwaggerHub API Auto Mocking',
            'url': 'https://virtserver.swaggerhub.com/luis-pintado-feverup/backend-test/1.0.0',
        }
    ],
)


@app.get(
    '/search',
    response_model=SearchGetResponse,
    responses={
        '400': {'model': SearchGetResponse1},
        '500': {'model': SearchGetResponse2},
    },
)
def search_events(
    starts_at: Optional[datetime] = None, ends_at: Optional[datetime] = None
) -> Union[SearchGetResponse, SearchGetResponse1, SearchGetResponse2]:
    """
    Lists the available events on a time range
    """
    pass
